apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: platformrepo
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/oli-hills/hackathon-platform
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: type1
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./base/
  prune: true
  sourceRef:
    kind: GitRepository
    name: platformrepo
